import "./globals.css";
import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
const urbanist = Urbanist({ subsets: ["latin"] });

//Components
import SideBar from "@/components/sidebar";
import Header from "@/components/header";

//Context
import DateContextProvider from "./utils/context/dateContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${urbanist.className} bg-white`}>
        <div className='flex h-screen'>
          <SideBar />
          <DateContextProvider>
            <div className="grow">
              <Header />
              {children}
            </div>
          </DateContextProvider>
        </div>
      </body>
    </html>
  );
}